openapi: 3.0.1
info:
  description: A simple application to handle tasks.
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: A TODO-Task list application
  version: 1.0.0
servers:
- url: https://localhost:8080/todoapp
paths:
  /task:
    get:
      operationId: getAllTasks
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/task'
                type: array
          description: a list of all tasks
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: generic error response
    post:
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
        required: false
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
          description: Created
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: error
  /task/{taskId}:
    delete:
      operationId: deleteTask
      parameters:
      - explode: false
        in: path
        name: taskId
        required: true
        schema:
          type: string
        style: simple
      responses:
        204:
          content: {}
          description: Deleted
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: error
    put:
      operationId: updateTask
      parameters:
      - explode: false
        in: path
        name: taskId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
        required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
          description: error
components:
  schemas:
    task:
      example:
        description: description
        id: id
        completed: true
      properties:
        id:
          readOnly: true
          type: string
        description:
          type: string
        completed:
          type: boolean
      required:
      - description
      type: object
    error:
      properties:
        id:
          format: int64
          type: integer
        message:
          type: string
      type: object
